In [1]:
path = "C:\\Users\\rafael.resende\\Documents\\GH\\Data-Science-Projects-with-Python\\"

In [2]:
#  Exercise 1
for counter in range(5):
    print(counter)

0
1
2
3
4


In [3]:
#  Exercise 2 - Carregar arquivo

In [4]:
import pandas as pd

In [5]:
df = pd.read_excel(path+"Chapter 1\\data\\default_of_credit_card_clients__courseware_version_1_21_19.xls")

In [6]:
df.shape

(30000, 25)

In [7]:
#  Exercise 3

In [8]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [9]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

In [10]:
df['ID'].nunique()

29687

In [11]:
df.shape

(30000, 25)

In [12]:
id_counts = df['ID'].value_counts()

In [13]:
id_counts.head()

30729bb5-55d7    2
327d06d5-ce7f    2
249b09c0-f4c7    2
9a75e346-c849    2
a7559852-f405    2
Name: ID, dtype: int64

In [14]:
id_counts.value_counts()

1    29374
2      313
Name: ID, dtype: int64

In [15]:
import numpy as np

In [16]:
np.random.seed(seed=24)

In [17]:
random_integers = np.random.randint(low=1,high=5,size=100)

In [18]:
random_integers[:5]

array([3, 4, 1, 4, 2])

In [19]:
is_equal_to_3 = random_integers == 3

In [20]:
is_equal_to_3[:5]

array([ True, False, False, False, False])

In [21]:
sum(is_equal_to_3)

22

In [22]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [23]:
#  Exercise 4

In [24]:
dupe_mask = id_counts == 2
dupe_mask[0:5]

30729bb5-55d7    True
327d06d5-ce7f    True
249b09c0-f4c7    True
9a75e346-c849    True
a7559852-f405    True
Name: ID, dtype: bool

In [25]:
id_counts.index[0:5]

Index(['30729bb5-55d7', '327d06d5-ce7f', '249b09c0-f4c7', '9a75e346-c849',
       'a7559852-f405'],
      dtype='object')

In [26]:
dupe_ids = id_counts.index[dupe_mask]

In [27]:
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

In [28]:
dupe_ids[0:5]

['30729bb5-55d7',
 '327d06d5-ce7f',
 '249b09c0-f4c7',
 '9a75e346-c849',
 'a7559852-f405']

In [29]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:].head(10)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
1827   327d06d5-ce7f      50000    1          3         1   32     0      0   
1927   327d06d5-ce7f          0    0          0         0    0     0      0   
6118   249b09c0-f4c7     360000    1          1         2   29    -1     -1   
6218   249b09c0-f4c7          0    0          0         0    0     0      0   
27333  30729bb5-55d7     110000    1          2         2   42     0      0   
27433  30729bb5-55d7          0    0          0         0    0     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
1827       0      0  ...      18891      19443      19478      2026      2021   
1927       0      0  ...          0          0          0         0         0   
6118      -1     -2  ...          0       7972       8275      1175         0   
6218       0      0  ...          0          0          0         0         0   
27333      2      2  ...      56309      58359     109312      5150      2000   
27433      0      0  ...          0          0          0         0         0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1827       1000      1001      1000       707                           0  
1927          0         0         0         0                           0  
6118          0      7972       435      2947                           0  
6218          0         0         0         0                           0  
27333         0      2800     54000         0                           0  
27433         0         0         0         0                           0  

[6 rows x 25 columns]

In [30]:
df_zero_mask = df == 0

In [31]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)

In [32]:
sum(feature_zero_mask)

315

In [33]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()     # pq esse ~ ???

In [34]:
df_clean_1.shape

(29685, 25)

In [35]:
df_clean_1['ID'].nunique()

29685

In [36]:
df_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29685 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   ID                          29685 non-null  object
 1   LIMIT_BAL                   29685 non-null  int64 
 2   SEX                         29685 non-null  int64 
 3   EDUCATION                   29685 non-null  int64 
 4   MARRIAGE                    29685 non-null  int64 
 5   AGE                         29685 non-null  int64 
 6   PAY_1                       29685 non-null  object
 7   PAY_2                       29685 non-null  int64 
 8   PAY_3                       29685 non-null  int64 
 9   PAY_4                       29685 non-null  int64 
 10  PAY_5                       29685 non-null  int64 
 11  PAY_6                       29685 non-null  int64 
 12  BILL_AMT1                   29685 non-null  int64 
 13  BILL_AMT2                   29685 non-null  in

In [37]:
df_clean_1['PAY_1'].head(5)

0     2
1    -1
2     0
3     0
4    -1
Name: PAY_1, dtype: object

In [38]:
df_clean_1['PAY_1'].value_counts()

0                13087
-1                5047
1                 3261
Not available     3021
-2                2476
2                 2378
3                  292
4                   63
5                   23
8                   17
6                   11
7                    9
Name: PAY_1, dtype: int64

In [39]:
valid_pay_1_mask = df_clean_1['PAY_1'] != 'Not available'
valid_pay_1_mask[0:5]

0    True
1    True
2    True
3    True
4    True
Name: PAY_1, dtype: bool

In [40]:
sum(valid_pay_1_mask)

26664

In [41]:
df_clean_2 = df_clean_1.loc[valid_pay_1_mask,:].copy()

In [42]:
df_clean_2.shape

(26664, 25)

In [43]:
df_clean_2['PAY_1'] = df_clean_2['PAY_1'].astype('int64')

In [44]:
df_clean_2[['PAY_1', 'PAY_2']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26664 entries, 0 to 29999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PAY_1   26664 non-null  int64
 1   PAY_2   26664 non-null  int64
dtypes: int64(2)
memory usage: 624.9 KB


In [45]:
#  Exercise 5 - Will show up here when the time comes. :)